# NOT USED ANYMORE!

# dependencies
#$(OBJSONEPOINT) $(OBJSMANYPOINTS) freespace.o : global.h defs.h mympi.h mpidefs.h metric.h coord.h \
#init.h definit.h makefile makehead.inc maketail.harm.deps.inc \
#maketail.harm.inc maketail.inc

#utoprim_2d.o : utoprim_2d.h utoprim_1d2d.h u2p_util.c utoprim_jon_eos.c
#utoprim_1d.o : utoprim_1d.h utoprim_1d2d.h u2p_util.c utoprim_jon_eos.c
#utoprim_1d_opt.o : utoprim_1d_opt.h u2p_util.c utoprim_jon_eos.c
#interpline.o : reconstructeno.h
#monointerp.o : reconstructeno.h smonointerp_static.h
#jmonointerp.o : reconstructeno.h
#smonointerp.o : smonointerp.h smonointerp_static.h reconstructeno.h
#utoprim_2d_final.o : u2p_defs.h u2p_util.c utoprim_jon_eos.c
#utoprim_jon.o : u2p_defs.h u2p_util.c utoprim_jon_eos.c
#utoprim_1d_final.o : u2p_defs.h u2p_util.c utoprim_jon_eos.c
#utoprim_5d2_final.o : u2p_defs.h u2p_util.c utoprim_jon_eos.c
#reconstructeno.o : reconstructeno.h reconstructeno_static.h


