
SRCSJONINTERP = \
jon_interp.c nrutil2.c jon_interp_mnewt.c coord.c nrutil.c ludcmp.c lubksb.c newt.c lnsrch.c fdjac.c fmin.c broydn.c qrdcmp.c rsolv.c qrupdt.c rotate.c ranc.c bcucof.c bcuint.c metric_tools.c mpi_fprintfs.c gaussj.c
#END

OBJSJONINTERP = \
jon_interp.o nrutil2.o jon_interp_mnewt.o coord.o nrutil.o ludcmp.o lubksb.o newt.o lnsrch.o fdjac.o fmin.o broydn.o qrdcmp.o rsolv.o qrupdt.o rotate.o ranc.o bcucof.o bcuint.o metric_tools.o mpi_fprintfs.o gaussj.o
#END

